name: release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout (e.g., main)'
        required: true
        default: 'main'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure workspace ownership
        run: echo "chown -R $USER $GITHUB_WORKSPACE" && sudo chown -R $USER $GITHUB_WORKSPACE

      # https://github.com/actions/checkout/blob/v3/README.md
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret as an environment variable
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.inputs.branch }}

      - name: Prepare release body
        run: |
          RELEASE_DATETIME=$(date -u +"%Y%m%dT%H%M%S")
          echo "RELEASE_TAG=$RELEASE_DATETIME" >> $GITHUB_ENV
          

      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lmshg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push slim image linux/amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: lmshg/tradingagents-cn:${{ env.RELEASE_TAG }}
          file: Dockerfile
          build-args: |
            LIGHTEN=1
          platforms: linux/amd64,linux/arm64
